/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListTemplatesRequest {
    /**
     * A unique identifier that allows for fetching the next set of templates
     */
    cursor?: string;
}
