/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         profile: undefined
 *     }
 */
export interface AddUserToSingleTenantsParams {
    profile?: Record<string, any>;
}
