/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface GetUserTokenResponse extends Courier.UserToken {
    status?: Courier.TokenStatus;
    /** The reason for the token status. */
    status_reason?: string;
}
