/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TokenStatus = "active" | "unknown" | "failed" | "revoked";

export const TokenStatus = {
    Active: "active",
    Unknown: "unknown",
    Failed: "failed",
    Revoked: "revoked",
} as const;
