/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface SubscriptionTopicNew {
    status: Courier.SubscriptionTopicStatus;
    /** Override channel routing with custom preferences. This will override any template prefernces that are set, but a user can still customize their preferences */
    has_custom_routing?: boolean;
    /** The default channels to send to this tenant when has_custom_routing is enabled */
    custom_routing?: Courier.ChannelClassification[];
}
