/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface TenantListResponse {
    /** A pointer to the next page of results. Defined only whenhas_more is set to true. */
    cursor?: string;
    /** Set to true when there are more pages that can be retrieved. */
    has_more: boolean;
    /** An array of Tenants */
    items: Courier.Tenant[];
    /**
     * A url that may be used to generate fetch the next set of results.
     * Defined only whenhas_more is set to true
     */
    next_url?: string;
    /** A url that may be used to generate these results. */
    url: string;
    /** Always set to "list". Represents the type of this object. */
    type: "list";
}
