/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface BulkMessageUserResponse extends Courier.InboundBulkMessageUser {
    status: Courier.BulkJobUserStatus;
    messageId?: string;
}
