/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface InboundBulkMessageUser {
    preferences?: Courier.RecipientPreferences;
    profile?: any;
    recipient?: string;
    data?: any;
    to?: Courier.UserRecipient;
}
