/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface JobDetails {
    definition: Courier.InboundBulkMessage;
    enqueued: number;
    failures: number;
    received: number;
    status: Courier.BulkJobStatus;
}
