/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         type: "string"
 *     }
 */
export interface GetMessageHistoryRequest {
    /**
     * A supported Message History type that will filter the events returned.
     */
    type?: string;
}
