/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import * as Courier from "../../..";

export class AlreadyExistsError extends errors.CourierError {
    constructor(body: Courier.AlreadyExists) {
        super({
            message: "AlreadyExistsError",
            statusCode: 409,
            body: body,
        });
        Object.setPrototypeOf(this, AlreadyExistsError.prototype);
    }
}
