/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import * as Courier from "../../..";

export class PaymentRequiredError extends errors.CourierError {
    constructor(body: Courier.PaymentRequired) {
        super({
            message: "PaymentRequiredError",
            statusCode: 402,
            body: body,
        });
        Object.setPrototypeOf(this, PaymentRequiredError.prototype);
    }
}
