/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Address {
    formatted: string;
    street_address: string;
    locality: string;
    region: string;
    postal_code: string;
    country: string;
}
