/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface AirshipProfile {
    audience: Courier.AirshipProfileAudience;
    device_types: (Courier.DeviceType | undefined)[];
}
