/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface GetListSubscriptionsList {
    id: string;
    /** List name */
    name: string;
    /** The date/time of when the list was created. Represented as a string in ISO format. */
    created: string;
    /** The date/time of when the list was updated. Represented as a string in ISO format. */
    updated: string;
    preferences?: Courier.RecipientPreferences;
}
