/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface Intercom {
    from: string;
    to: Courier.IntercomRecipient;
}
