/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export type MsTeams =
    | Courier.SendToMsTeamsUserId
    | Courier.SendToMsTeamsEmail
    | Courier.SendToMsTeamsChannelId
    | Courier.SendToMsTeamsConversationId
    | Courier.SendToMsTeamsChannelName;
