/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface ProfileUpdateRequest {
    /** List of patch operations to apply to the profile. */
    patch: Courier.UserProfilePatch[];
}
