/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface SendToMsTeamsChannelName extends Courier.MsTeamsBaseProperties {
    channel_name: string;
    team_id: string;
}
