/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface SendToSlackUserId extends Courier.SlackBaseProperties {
    user_id: string;
}
