/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UserProfilePatch {
    /** The operation to perform. */
    op: string;
    /** The JSON path specifying the part of the profile to operate on. */
    path: string;
    /** The value for the operation. */
    value: string;
}
