/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface UserProfile {
    address: Courier.Address;
    birthdate: string;
    email: string;
    email_verified: boolean;
    family_name: string;
    gender: string;
    given_name: string;
    locale: string;
    middle_name: string;
    name: string;
    nickname: string;
    phone_number: string;
    phone_number_verified: boolean;
    picture: string;
    preferred_name: string;
    profile: string;
    sub: string;
    updated_at: string;
    website: string;
    zoneinfo: string;
    /** A free form object. Due to a limitation of the API Explorer, you can only enter string key/values below, but this API accepts more complex object structures. */
    custom?: any;
    airship: Courier.AirshipProfile;
    apn: string;
    target_arn: string;
    discord: Courier.Discord;
    expo: Courier.Expo;
    facebookPSID: string;
    firebaseToken: string;
    intercom: Courier.Intercom;
    ms_teams: Courier.MsTeams;
}
