/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WebhookProfileType = "limited" | "expanded";

export const WebhookProfileType = {
    Limited: "limited",
    Expanded: "expanded",
} as const;
