/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../../..";

export interface PutUserTokenOpts {
    user_id: string;
    token: Courier.users.UserToken;
}
