/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../../..";

export interface UserToken {
    /** Full body of the token. Must match token in URL. */
    token?: string;
    provider_key: Courier.users.ProviderKey;
    /** ISO 8601 formatted date the token expires. Defaults to 2 months. Set to false to disable expiration. */
    expiry_date?: Courier.users.ExpiryDate;
    /** Properties sent to the provider along with the token */
    properties?: any;
    /** Information about the device the token is associated with. */
    device?: Courier.users.Device;
    /** Information about the device the token is associated with. */
    tracking?: Courier.users.Tracking;
}
