/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface ListGetSubscriptionsResponse {
    paging: Courier.Paging;
    items: Courier.ListSubscriptionRecipient[];
}
