/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface PutSubscriptionsRecipient {
    recipientId: string;
    preferences?: Courier.RecipientPreferences;
}
