/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface AudienceMemberListResponse {
    items: Courier.AudienceMember[];
    paging: Courier.Paging;
}
