/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

/**
 * The operator to use for filtering
 */
export interface NestedFilterConfig extends Courier.BaseFilterConfig {
    rules: Courier.FilterConfig[];
}
