/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../../../../index";

/**
 * @example
 *     {
 *         topic: {
 *             status: Courier.PreferenceStatus.OptedIn,
 *             has_custom_routing: true,
 *             custom_routing: [Courier.ChannelClassification.Inbox, Courier.ChannelClassification.Email]
 *         }
 *     }
 */
export interface UserPreferencesUpdateParams {
    topic: Courier.users.TopicPreferenceUpdate;
}
