/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UserPreferencesParams {
    /** Query the preferences of a user for this specific tenant context. */
    tenant_id?: string;
}
