/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface MessageDetailsExtended extends Courier.MessageDetails {
    providers?: Record<string, any>[];
}
