/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MessageStatus =
    /**
     * The recipient has clicked on any link in the message at least one time. */
    | "CLICKED"
    /**
     * The provider successfully delivered the message to the recipient. */
    | "DELIVERED"
    /**
     * The request has been received to send a message, is waiting in the work queue. */
    | "ENQUEUED"
    /**
     * The recipient has opened the message at least one time. */
    | "OPENED"
    /**
     * The message has been canceled such that it will not be delivered. */
    | "CANCELED"
    /**
     * The message has been accepted by the provider. */
    | "SENT"
    /**
     * The message could not be delivered to at least one provider, or the provider could not deliver the message to the recipient. This can happen for multiple reasons: an error, insufficient profile data, invalid notification setup, invalid integration configuration, etc. */
    | "UNDELIVERABLE"
    /**
     * Could not find a corresponding notification or event for the messages. */
    | "UNMAPPED"
    /**
     * The message could not be routed to any channel or provider. This can happen for multiple reasons: insufficient profile data, invalid notification setup, invalid integration configuration, etc. */
    | "UNROUTABLE";

export const MessageStatus = {
    Clicked: "CLICKED",
    Delivered: "DELIVERED",
    Enqueued: "ENQUEUED",
    Opened: "OPENED",
    Canceled: "CANCELED",
    Sent: "SENT",
    Undeliverable: "UNDELIVERABLE",
    Unmapped: "UNMAPPED",
    Unroutable: "UNROUTABLE",
} as const;
