/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface RenderedMessageContent {
    /** The html content of the rendered message. */
    html: string;
    /** The title of the rendered message. */
    title: string;
    /** The body of the rendered message. */
    body: string;
    /** The subject of the rendered message. */
    subject: string;
    /** The text of the rendered message. */
    text: string;
    /** The blocks of the rendered message. */
    blocks: Courier.RenderedMessageBlock[];
}
