/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RenderedMessageBlock {
    /** The block type of the rendered message block. */
    type: string;
    /** The block text of the rendered message block. */
    text: string;
}
