/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetSubscriptionForListRequest {
    /**
     * A unique identifier that allows for fetching the next set of list subscriptions
     */
    cursor?: string;
}
