/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../../index";

/**
 * @example
 *     {
 *         preferences: {
 *             categories: {},
 *             notifications: {}
 *         }
 *     }
 */
export interface SubscribeUserToListRequest {
    preferences?: Courier.RecipientPreferences;
}
