/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         cursor: "string"
 *     }
 */
export interface NotificationListParams {
    cursor?: string;
}
