/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../../index";

/**
 * @example
 *     {
 *         checks: [{
 *                 id: "string",
 *                 status: Courier.CheckStatus.Resolved,
 *                 type: "custom"
 *             }]
 *     }
 */
export interface SubmissionChecksReplaceParams {
    checks: Courier.BaseCheck[];
}
