/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../../index";

/**
 * @example
 *     {
 *         message: {
 *             message: {},
 *             brand: "string",
 *             data: {
 *                 "string": {
 *                     "key": "value"
 *                 }
 *             },
 *             event: "string",
 *             locale: {
 *                 "string": {
 *                     "key": "value"
 *                 }
 *             },
 *             override: {
 *                 "key": "value"
 *             }
 *         }
 *     }
 */
export interface BulkCreateJobParams {
    message: Courier.InboundBulkMessage;
}
