/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface BulkGetUsersParams {
    /**
     * A unique identifier that allows for fetching the next set of users added to the bulk job
     */
    cursor?: string;
}
