/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../../index";

/**
 * @example
 *     {
 *         name: "name",
 *         settings: undefined,
 *         snippets: undefined
 *     }
 */
export interface BrandUpdateParameters {
    /** The name of the brand. */
    name: string;
    settings?: Courier.BrandSettings;
    snippets?: Courier.BrandSnippets;
}
