/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListBrandsRequest {
    /**
     * A unique identifier that allows for fetching the next set of brands.
     */
    cursor?: string;
}
