/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface RoutingStrategy {
    /** The method for selecting channels to send the message with. Value can be either 'single' or 'all'. If not provided will default to 'single' */
    method: Courier.RoutingStrategyMethod;
    /** An array of valid channel identifiers (like email, push, sms, etc.) and additional routing nodes. */
    channels: Courier.ChannelIdentifier[];
}
