/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TagData {
    /** A unique identifier of the tag. */
    id: string;
    /** Name of the tag. */
    name: string;
}
