/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AudienceMembersListParams {
    /**
     * A unique identifier that allows for fetching the next set of members
     */
    cursor?: string;
}
