/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

/**
 * @example
 *     {
 *         action: "throttle",
 *         max_allowed: 1,
 *         period: "PT5M",
 *         scope: Courier.AutomationThrottleScope.Dynamic,
 *         throttle_key: "refs.data.throttle_key",
 *         should_alert: false,
 *         on_throttle: {
 *             $node_id: "on-throttle-node-ref"
 *         }
 *     }
 */
export interface AutomationThrottleStep extends Courier.AutomationStep {
    action: "throttle";
    /** Maximum number of allowed notifications in that timeframe */
    max_allowed: number;
    /** Defines the throttle period which corresponds to the max_allowed. Specified as an ISO 8601 duration, https://en.wikipedia.org/wiki/ISO_8601#Durations */
    period: string;
    scope: Courier.AutomationThrottleScope;
    /** If using scope=dynamic, provide the reference (e.g., refs.data.throttle_key) to the how the throttle should be identified */
    throttle_key?: string;
    /** Value must be true */
    should_alert: false;
    on_throttle: Courier.AutomationThrottleOnThrottle;
}
