/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface AutomationSendStep extends Courier.AutomationStep {
    action: "send";
    brand?: string;
    data?: Record<string, any>;
    override?: Record<string, any>;
    profile?: any;
    recipient?: string;
    template?: string;
}
