/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface AutomationInvokeParams {
    brand?: string;
    data?: Record<string, any>;
    profile?: Courier.Profile | undefined;
    recipient?: string;
    template?: string;
}
