/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface AutomationFetchDataWebhook {
    body?: Record<string, any>;
    headers?: Record<string, any>;
    params?: Record<string, any>;
    method: Courier.AutomationFetchDataWebhookMethod;
    url: string;
}
