/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface AutomationInvokeStep extends Courier.AutomationStep {
    action: "invoke";
    template: string;
}
