/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface BadRequest extends Courier.BaseError {
    type: "invalid_request_error";
}
