/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface ListTemplateTenantAssociation extends Courier.BaseTemplateTenantAssociation {
    data: Courier.TenantTemplateDataNoContent;
}
