/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface NotificationPreferenceDetails {
    status: Courier.PreferenceStatus;
    rules?: Courier.Rule[];
    channel_preferences?: Courier.ChannelPreference[];
}
