/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface SingleTemplateTenantAssociation extends Courier.BaseTemplateTenantAssociation {
    data: Courier.TenantTemplateData;
}
