/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface BaseCheck {
    id: string;
    status: Courier.CheckStatus;
    type: "custom";
}
