/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BlockType =
    | "action"
    | "divider"
    | "image"
    | "jsonnet"
    | "list"
    | "markdown"
    | "quote"
    | "template"
    | "text";
export const BlockType = {
    Action: "action",
    Divider: "divider",
    Image: "image",
    Jsonnet: "jsonnet",
    List: "list",
    Markdown: "markdown",
    Quote: "quote",
    Template: "template",
    Text: "text",
} as const;
