/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface MessageRouting {
    method: Courier.MessageRoutingMethod;
    channels: Courier.MessageRoutingChannel[];
}
