/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface NotificationChannel {
    id: string;
    type?: string;
    content?: Courier.NotificationChannelContent;
    locales?: Record<string, Courier.NotificationChannelContent>;
    checksum?: string;
}
