/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface NotificationBlock {
    alias?: string;
    context?: string;
    id: string;
    type: Courier.BlockType;
    content?: Courier.NotificationContent;
    locales?: Record<string, Courier.NotificationContent>;
    checksum?: string;
}
