/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface Notification {
    created_at: number;
    updated_at: number;
    id: string;
    routing: Courier.MessageRouting;
    tags?: Courier.NotificationTag;
    title?: string;
    topic_id: string;
    note: string;
}
