/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface Notification {
    created_at: number;
    id: string;
    routing: Courier.MessageRouting;
}
