/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Preferences } from "../resources/preferences/client/Client";
import { Tenants } from "../resources/tenants/client/Client";
import { Tokens } from "../resources/tokens/client/Client";

export declare namespace Users {
    export interface Options {
        environment?: core.Supplier<environments.CourierEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        authorizationToken?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }
}

export class Users {
    protected _preferences: Preferences | undefined;
    protected _tenants: Tenants | undefined;
    protected _tokens: Tokens | undefined;

    constructor(protected readonly _options: Users.Options = {}) {}

    public get preferences(): Preferences {
        return (this._preferences ??= new Preferences(this._options));
    }

    public get tenants(): Tenants {
        return (this._tenants ??= new Tenants(this._options));
    }

    public get tokens(): Tokens {
        return (this._tokens ??= new Tokens(this._options));
    }
}
