/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface BrandsResponse {
    paging: Courier.Paging;
    results: Courier.Brand[];
}
