/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface BrandSettings {
    colors?: Courier.BrandColors;
    inapp?: any;
    email?: Courier.Email;
}
