/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface AudienceRecipient {
    /** A unique identifier associated with an Audience. A message will be sent to each user in the audience. */
    audience_id: string;
    data?: Courier.MessageData;
    filters?: Courier.AudienceFilter[];
}
