/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface BrandSettingsEmail {
    templateOverride?: Courier.BrandTemplateOverride;
    head?: Courier.EmailHead;
    footer?: Courier.EmailFooter;
    header?: Courier.EmailHeader;
}
