/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ChannelSource = "subscription" | "list" | "recipient";

export const ChannelSource = {
    Subscription: "subscription",
    List: "list",
    Recipient: "recipient",
} as const;
