/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

/**
 * Renders a dividing line between elements.
 */
export interface ElementalDividerNode extends Courier.ElementalBaseNode {
    /** The CSS color to render the line with. For example, `#fff` */
    color?: string;
}
