/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

/**
 * Represents a body of text to be rendered inside of the notification.
 */
export interface ElementalTextNode extends Courier.ElementalBaseNode {
    /**
     * The text content displayed in the notification. Either this
     * field must be specified, or the elements field
     */
    content: string;
    /** Text alignment. */
    align: Courier.TextAlign;
    /** Allows the text to be rendered as a heading level. */
    text_style?: Courier.TextStyle;
    /** Specifies the color of text. Can be any valid css color value */
    color?: string;
    /** Apply bold to the text */
    bold?: string;
    /** Apply italics to the text */
    italic?: string;
    /** Apply a strike through the text */
    strikethrough?: string;
    /** Apply an underline to the text */
    underline?: string;
    /** Region specific content. See [locales docs](https://www.courier.com/docs/platform/content/elemental/locales/) for more details. */
    locales?: Courier.Locales | undefined;
    format?: "markdown";
}
