/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../..";

export interface Expiry {
    /** An epoch timestamp or ISO8601 timestamp with timezone `(YYYY-MM-DDThh:mm:ss.sTZD)` that describes the time in which a message expires. */
    expires_at?: string;
    /** A duration in the form of milliseconds or an ISO8601 Duration format (i.e. P1DT4H). */
    expires_in: Courier.ExpiresInType;
}
