/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface IProfilePreferences {
    categories?: Courier.IPreferences;
    notifications: Courier.IPreferences;
    templateId?: string;
}
