/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MessagePreferences {
    /** The ID of the subscription topic you want to apply to the message. If this is a templated message, it will override the subscription topic if already associated */
    subscription_topic_id: string;
}
