/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface MessageProvidersType {
    /** Provider specific overrides. */
    override?: Record<string, any>;
    /**
     * A JavaScript conditional expression to determine if the message should
     * be sent through the provider. Has access to the data and profile object.
     * Only applies when a custom routing strategy is defined.
     * For example, `data.name === profile.name`
     */
    if?: string;
    timeouts?: number;
    metadata?: Courier.Metadata;
}
