/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface MessageProvidersType {
    /** Provider specific overrides. */
    override?: Record<string, any>;
    /**
     * A JavaScript conditional expression to determine if the message should be sent
     * through the channel. Has access to the data and profile object. For example,
     * `data.name === profile.name`
     */
    if?: string;
    timeouts?: number;
    metadata?: Courier.Metadata;
}
