/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export type Recipient =
    | Courier.AudienceRecipient
    | Courier.ListRecipient
    | Courier.ListPatternRecipient
    | Courier.UserRecipient
    | Courier.SlackRecipient
    | Courier.MsTeamsRecipient
    | Courier.RecipientData
    | Courier.PagerdutyRecipient
    | Courier.WebhookRecipient;
