/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index";

export interface RoutingStrategyProvider {
    name: string;
    config?: Record<string, any>;
    if?: string;
    metadata: Courier.Metadata;
}
