/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RoutingMethod = "all" | "single";
export const RoutingMethod = {
    All: "all",
    Single: "single",
} as const;
