/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Courier from "../../../index.js";

export interface UserRecipient extends Courier.UserRecipientType {
    /** Use `tenant_id` instad. */
    account_id?: string;
    /** Context information such as tenant_id to send the notification with. */
    context?: Courier.MessageContext;
    data?: Courier.MessageData;
    email?: string;
    /** The user's preferred ISO 639-1 language code. */
    locale?: string;
    user_id?: string;
    phone_number?: string;
    preferences?: Courier.IProfilePreferences;
    /**
     * An id of a tenant, [see tenants api docs](https://www.courier.com/docs/reference/tenants).
     * Will load brand, default preferences and any other base context data associated with this tenant.
     */
    tenant_id?: string;
}
